ALTER TABLE "employee_profiles" ADD COLUMN "permanent_address" text;--> statement-breakpoint
ALTER TABLE "employee_profiles" ADD COLUMN "facebook_id" text;--> statement-breakpoint
ALTER TABLE "employee_profiles" ADD COLUMN "linkedin_url" text;--> statement-breakpoint
ALTER TABLE "employee_profiles" ADD COLUMN "instagram_handle" text;--> statement-breakpoint
ALTER TABLE "employee_profiles" ADD COLUMN "emergency_contact_relationship" text;--> statement-breakpoint
ALTER TABLE "employee_profiles" ADD COLUMN "gender" text;--> statement-breakpoint
ALTER TABLE "employee_profiles" ADD COLUMN "blood_group" text;--> statement-breakpoint
ALTER TABLE "employee_profiles" ADD COLUMN "dob_documents" date;--> statement-breakpoint
ALTER TABLE "employee_profiles" ADD COLUMN "dob_actual" date;--> statement-breakpoint
ALTER TABLE "employee_profiles" ADD COLUMN "father_name" text;--> statement-breakpoint
ALTER TABLE "employee_profiles" ADD COLUMN "father_contact" text;--> statement-breakpoint
ALTER TABLE "employee_profiles" ADD COLUMN "mother_name" text;--> statement-breakpoint
ALTER TABLE "employee_profiles" ADD COLUMN "mother_dob" date;--> statement-breakpoint
ALTER TABLE "employee_profiles" ADD COLUMN "mother_contact" text;--> statement-breakpoint
ALTER TABLE "employee_profiles" ADD COLUMN "religion" text;--> statement-breakpoint
ALTER TABLE "employee_profiles" ADD COLUMN "mother_tongue" text;--> statement-breakpoint
ALTER TABLE "employee_profiles" ADD COLUMN "marital_status" text;--> statement-breakpoint
ALTER TABLE "employee_profiles" ADD COLUMN "spouse_name" text;--> statement-breakpoint
ALTER TABLE "employee_profiles" ADD COLUMN "spouse_dob" text;--> statement-breakpoint
ALTER TABLE "employee_profiles" ADD COLUMN "spouse_contact" text;--> statement-breakpoint
ALTER TABLE "employee_profiles" ADD COLUMN "anniversary_date" text;--> statement-breakpoint
ALTER TABLE "employee_profiles" ADD COLUMN "under_graduate" text;--> statement-breakpoint
ALTER TABLE "employee_profiles" ADD COLUMN "graduate" text;--> statement-breakpoint
ALTER TABLE "employee_profiles" ADD COLUMN "masters" text;--> statement-breakpoint
ALTER TABLE "employee_profiles" ADD COLUMN "diploma_others" text;--> statement-breakpoint
ALTER TABLE "employee_profiles" ADD COLUMN "total_experience" text;--> statement-breakpoint
ALTER TABLE "employee_profiles" ADD COLUMN "aadhar_number" text;--> statement-breakpoint
ALTER TABLE "employee_profiles" ADD COLUMN "pan_number" text;--> statement-breakpoint
ALTER TABLE "employee_profiles" ADD COLUMN "uan_number" text;--> statement-breakpoint
ALTER TABLE "employee_profiles" ADD COLUMN "driving_license_number" text;--> statement-breakpoint
ALTER TABLE "employee_profiles" ADD COLUMN "voters_id_number" text;--> statement-breakpoint
ALTER TABLE "employee_profiles" ADD COLUMN "passport_number" text;--> statement-breakpoint
ALTER TABLE "employee_profiles" ADD COLUMN "bank_account_holder_name" text;--> statement-breakpoint
ALTER TABLE "employee_profiles" ADD COLUMN "bank_name" text;--> statement-breakpoint
ALTER TABLE "employee_profiles" ADD COLUMN "team_and_floor" text;--> statement-breakpoint
ALTER TABLE "employee_profiles" ADD COLUMN "sub_process_department" text;--> statement-breakpoint
ALTER TABLE "employee_profiles" ADD COLUMN "floor_details" text;--> statement-breakpoint
ALTER TABLE "employee_profiles" ADD COLUMN "date_of_confirmation" date;--> statement-breakpoint
ALTER TABLE "employee_profiles" ADD COLUMN "office_timings" text;--> statement-breakpoint
ALTER TABLE "employee_profiles" ADD COLUMN "shift_type" text;--> statement-breakpoint
ALTER TABLE "employee_profiles" ADD COLUMN "direct_reporting_authority" text;--> statement-breakpoint
ALTER TABLE "employee_profiles" ADD COLUMN "dotted_line_reporting_authority" text;--> statement-breakpoint
ALTER TABLE "employee_profiles" ADD COLUMN "source_referred_by" text;